#include <tmplang/Lowering/Dialect/HIR/Types.h>

#include <llvm/ADT/TypeSwitch.h>
#include <mlir/IR/DialectImplementation.h>
#include <mlir/IR/OpImplementation.h>
#include <mlir/Parser/Parser.h>
#include <tmplang/ADT/PrintUtils.h>

using namespace tmplang;

/// Include all autogenerated code for types
#define GET_TYPEDEF_CLASSES
#include <tmplang/Lowering/Dialect/HIR/TmplangHIROpsTypes.cpp.inc>

void TmplangHIRDialect::registerTypes() {
  addTypes<
#define GET_TYPEDEF_LIST
#include <tmplang/Lowering/Dialect/HIR/TmplangHIROpsTypes.cpp.inc>
      >();
}

/*static*/ bool TmplangType::classof(mlir::Type type) {
  return llvm::isa<TmplangHIRDialect>(type.getDialect());
}
